# -*- coding: utf-8 -*-
"""entity_preserving_and_rephraser.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1mjYt5lhjLEsFB2tLeHQ4XAq4U-yGfPSE

Install dependencies
"""

# Install necessary Python libraries for natural language processing, transformers, and data handling.
!pip install spacy "transformers>=4.30" datasets accelerate sentencepiece evaluate rouge_score

# Download the small English language model for spaCy.
!python -m spacy download en_core_web_sm

# ============================================
# CREATE + DOWNLOAD GOLD ENTITY DATASET (400)
# ============================================

import json
import random
from google.colab import files

tools = ["Docker", "Jenkins", "Kubernetes", "GitHub", "Jira"]
issue_prefixes = ["BUG", "TASK", "STORY", "JIRA"]

gold_data = []

for _ in range(400):
    tool = random.choice(tools)
    sprint = random.randint(1, 10)
    issue = f"{random.choice(issue_prefixes)}-{random.randint(100,999)}"

    text = (
        f"The deployment failed in sprint {sprint} due to a configuration "
        f"issue in {tool} under ticket {issue}."
    )

    entities = []

    # ISSUE_ID
    start = text.find(issue)
    entities.append([start, start + len(issue), "ISSUE_ID"])

    # SPRINT
    sprint_text = f"sprint {sprint}"
    start = text.find(sprint_text)
    entities.append([start, start + len(sprint_text), "SPRINT"])

    # TOOL
    start = text.find(tool)
    entities.append([start, start + len(tool), "TOOL"])

    gold_data.append({
        "text": text,
        "entities": entities
    })

path = "gold_entity_preserving_ner_dataset.json"
with open(path, "w") as f:
    json.dump(gold_data, f, indent=2)

print("Gold dataset created:", path)
print("Total samples:", len(gold_data))

# Download
files.download(path)

from google.colab import files
files.upload()

"""Imports"""

# Import pandas for data manipulation.
import pandas as pd
# Import numpy for numerical operations.
import numpy as np
# Import spacy for natural language processing.
import spacy
# Import EntityRuler to add custom entity recognition rules to spaCy.
from spacy.pipeline import EntityRuler

# Import T5 tokenizer and model for conditional text generation from Hugging Face Transformers.
from transformers import T5Tokenizer, T5ForConditionalGeneration
# Import Trainer and TrainingArguments for model training from Hugging Face Transformers.
from transformers import Trainer, TrainingArguments
# Import Dataset for creating datasets compatible with Hugging Face Transformers.
from datasets import Dataset

# Import torch for deep learning operations, as it's the backend for Transformers.
import torch

"""Load spaCy + add Agile-specific rules"""

# Load the pre-trained small English language model from spaCy.
nlp = spacy.load("en_core_web_sm")

# Define custom patterns for Agile-related entities.
# ISSUE_ID: Recognizes patterns like 'BUG-123' or 'JIRA-456'.
# SPRINT: Recognizes 'sprint' followed by a digit.
# TOOL: Recognizes specific tool names like 'Docker', 'Jenkins', 'Kubernetes'.
patterns = [
    {"label": "ISSUE_ID", "pattern": [{"TEXT": {"REGEX": "[A-Z]+-[0-9]+"}}]}, # Pattern for issue IDs
    {"label": "SPRINT", "pattern": [{"LOWER": "sprint"}, {"IS_DIGIT": True}]}, # Pattern for sprint numbers
    {"label": "TOOL", "pattern": "Docker"},
    {"label": "TOOL", "pattern": "Jenkins"},
    {"label": "TOOL", "pattern": "Kubernetes"}
]

# Add the EntityRuler to the spaCy pipeline by its string name before the 'ner' component.
# The add_pipe method returns the newly created component, which we can then add patterns to.
ruler = nlp.add_pipe("entity_ruler", before="ner")
# Add the defined patterns to the EntityRuler.
ruler.add_patterns(patterns)

print("spaCy entity detector ready.")

"""Load Gold Dataset"""

# ==============================
# NER EVALUATION – LOAD GOLD DATA
# ==============================

import json

with open("gold_entity_preserving_ner_dataset.json", "r") as f:
    gold_data = json.load(f)

print("Gold dataset loaded")
print("Total samples:", len(gold_data))

"""Prepare spaCy Evaluation Examples"""

# ==================================
# PREPARE spaCy EVALUATION EXAMPLES (FIXED)
# ==================================

from spacy.training import Example

examples = []

for item in gold_data:
    doc = nlp(item["text"])   # ✅ RUN FULL PIPELINE
    example = Example.from_dict(doc, {"entities": item["entities"]})
    examples.append(example)

print("spaCy evaluation examples prepared correctly")

"""Compute NER Metrics"""

# ============================
# spaCy NER PERFORMANCE METRICS
# ============================

from spacy.scorer import Scorer

scorer = Scorer()
scores = scorer.score(examples)

print("===== ENTITY DETECTION RESULTS =====")
print(f"Precision : {scores['ents_p']:.3f}")
print(f"Recall    : {scores['ents_r']:.3f}")
print(f"F1-score  : {scores['ents_f']:.3f}")

"""Per-Entity Breakdown"""

# ============================
# PER-ENTITY PERFORMANCE
# ============================

print("\nPer-Entity Scores:")
for label, metrics in scores["ents_per_type"].items():
    print(
        f"{label:10s} | "
        f"P: {metrics['p']:.2f} | "
        f"R: {metrics['r']:.2f} | "
        f"F1: {metrics['f']:.2f}"
    )

"""Test entity detection"""

# Define a sample text to test the entity detection.
text = "api fails sprint 5 docker issue BUG-123"
# Process the text with the configured spaCy pipeline.
doc = nlp(text)

# Extract and print the recognized entities and their labels.
[(ent.text, ent.label_) for ent in doc.ents]

"""Masking & restoration functions"""

def mask_entities(text, doc):
    """Masks recognized entities in a text with placeholder tokens (e.g., ENTITY_1)."""
    entity_map = {}
    masked_text = text
    # Iterate through each recognized entity.
    for i, ent in enumerate(doc.ents):
        key = f"ENTITY_{i+1}"
        entity_map[key] = ent.text  # Store the original entity text with its placeholder key.
        masked_text = masked_text.replace(ent.text, key) # Replace the entity in the text with the placeholder.
    return masked_text, entity_map

def restore_entities(text, entity_map):
    """Restores original entities in a text from placeholder tokens using an entity map."""
    # Iterate through the entity map and replace placeholders with original entity texts.
    for key, value in entity_map.items():
        text = text.replace(key, value)
    return text

"""Create training dataset"""

from datasets import Dataset

inputs, outputs = [], []

for item in gold_data:
    text = item["text"]
    doc = nlp(text)
    masked_text, entity_map = mask_entities(text, doc)

    instr = (
        "Instruction: Rewrite the Agile idea clearly and professionally. "
        "Do not modify ENTITY tokens. Tone: neutral.\n"
        f"Input: {masked_text}"
    )
    # Target should KEEP the ENTITY placeholders; don't use the real entities here
    target = masked_text  # or a paraphrase that preserves ENTITY_ tokens

    inputs.append(instr)
    outputs.append(target)

dataset = Dataset.from_dict({"input": inputs, "output": outputs})
print("Full dataset size:", len(dataset))

# Train/validation split (10% for validation, reproducible with seed)
train_test = dataset.train_test_split(test_size=0.1, seed=42)
train_ds, val_ds = train_test["train"], train_test["test"]
print("Train size:", len(train_ds), "| Val size:", len(val_ds))

"""Load tokenizer & model"""

# Specify the name of the pre-trained T5 model to use.
model_name = "google/flan-t5-base"

# Load the tokenizer associated with the specified T5 model.
tokenizer = T5Tokenizer.from_pretrained(model_name)
# Load the T5 model for conditional generation.
model = T5ForConditionalGeneration.from_pretrained(model_name)

"""Tokenization"""

def tokenize(batch):
    inputs_tok = tokenizer(
        batch["input"],
        truncation=True,
        padding="max_length",
        max_length=256,
    )
    outputs_tok = tokenizer(
        batch["output"],
        truncation=True,
        padding="max_length",
        max_length=256,
    )
    inputs_tok["labels"] = outputs_tok["input_ids"]
    return inputs_tok

tokenized_train = train_ds.map(tokenize, batched=True)
tokenized_val   = val_ds.map(tokenize, batched=True)

"""Training arguments"""

training_args = TrainingArguments(
    output_dir="./entity_rephraser",
    learning_rate=2e-5,
    per_device_train_batch_size=4,
    num_train_epochs=5,
    save_strategy="epoch",
    logging_steps=10,
    report_to="none",
)

"""Train"""

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=tokenized_train,
    eval_dataset=tokenized_val,  # use validation set for monitoring
)

trainer.train()

"""```
Here's a detailed prompt for VS Code Copilot to help you implement a Python backend (e.g., using FastAPI or Flask) that utilizes the previously trained spaCy and T5 models for entity-preserving text rephrasing. This backend will serve a Vite React frontend.

---START COPILOT PROMPT---

**Goal**: Implement a RESTful API endpoint in Python to perform entity-preserving text rephrasing using pre-trained spaCy and T5 models. This API will be consumed by a Vite React frontend.

**Models to Load**:
1.  **spaCy NER Model**: Located at `./entity_ner_model`
2.  **T5 Rephrasing Model**: Located at `./entity_rephraser_model`
3.  **T5 Tokenizer**: Associated with the T5 rephrasing model.

**Dependencies**: Ensure `spacy`, `transformers`, `torch`, and your chosen web framework (e.g., `fastapi`, `uvicorn` for FastAPI, `flask` for Flask) are installed in the backend environment.

**Core Logic - Utility Functions**:
Before implementing the API endpoint, define the following two Python functions to handle entity masking and restoration. These are crucial for preserving entities during rephrasing.

```python
def mask_entities(text: str, doc: spacy.tokens.Doc):
    '''
    Masks recognized entities in a text with placeholder tokens (e.g., ENTITY_1).
    Args:
        text (str): The original text.
        doc (spacy.tokens.Doc): The spaCy Doc object containing recognized entities.
    Returns:
        tuple[str, dict[str, str]]: A tuple containing the masked text and a dictionary
                                    mapping placeholder keys (e.g., 'ENTITY_1') to original entity texts.
    '''
    entity_map = {}
    masked_text = text
    # Iterate through each recognized entity and replace it with a placeholder.
    # Ensure replacement is done carefully to avoid issues with overlapping entities or partial replacements.
    # A robust approach might involve replacing from longest to shortest entities, or using regex with word boundaries.
    # For simplicity, assuming no overlapping entities for this task:
    for i, ent in enumerate(sorted(doc.ents, key=lambda e: len(e.text), reverse=True)): # Replace longest first
        key = f"ENTITY_{i+1}"
        entity_map[key] = ent.text
        masked_text = masked_text.replace(ent.text, key)
    return masked_text, entity_map

def restore_entities(text: str, entity_map: dict[str, str]) -> str:
    '''
    Restores original entities in a text from placeholder tokens using an entity map.
    Args:
        text (str): The text containing entity placeholders.
        entity_map (dict[str, str]): A dictionary mapping placeholder keys to original entity texts.
    Returns:
        str: The text with original entities restored.
    '''
    # Iterate through the entity map and replace placeholders with original entity texts.
    # Ensure replacement is done from longest key to shortest to avoid partial replacements (e.g., replacing ENTITY_1 before ENTITY_10).
    for key in sorted(entity_map.keys(), key=len, reverse=True):
        value = entity_map[key]
        text = text.replace(key, value)
    return text
```

**API Endpoint Details**:

*   **Endpoint**: `/api/rephrase` (or similar, configurable)
*   **Method**: `POST`

*   **Input Parameters (Request Body - JSON)**:
    ```json
    {
      "text": "string"
    }
    ```
    *   `text` (string, required): The raw text string that needs to be rephrased.

*   **Processing Steps on Backend**:
    1.  Receive the `text` from the incoming POST request.
    2.  **Entity Detection (spaCy)**: Process the `text` with the loaded `nlp` (spaCy) model to identify entities.
        ```python
        doc = nlp(text)
        ```
    3.  **Mask Entities**: Call `mask_entities(text, doc)` to replace detected entities with `ENTITY_X` placeholders.
        ```python
        masked_text, entity_map = mask_entities(text, doc)
        ```
    4.  **Prepare T5 Input**: Construct the input string for the T5 model with the specific instruction and masked text. **Crucially, use the `masked_text` here, not the original.**
        ```python
        instruction = (
            "Instruction: Rewrite the Agile idea clearly and professionally. "
            "Do not modify ENTITY tokens. Tone: neutral.\n"
            f"Input: {masked_text}"
        )
        ```
    5.  **T5 Generation**: Tokenize the `instruction` and pass it to the loaded T5 model for text generation.
        ```python
        input_ids = tokenizer(instruction, return_tensors="pt").input_ids
        # Move input_ids to model's device (CPU/GPU)
        device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        input_ids = input_ids.to(device)
        model.to(device) # Ensure model is on the correct device

        with torch.no_grad():
            outputs = model.generate(input_ids, max_length=128, num_beams=5, early_stopping=True)
        generated_masked_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        ```
    6.  **Restore Entities**: Call `restore_entities(generated_masked_text, entity_map)` to replace the `ENTITY_X` placeholders in the T5 output with their original values.
        ```python
        final_rephrased_text = restore_entities(generated_masked_text, entity_map)
        ```

*   **Output (Response Body - JSON)**:
    ```json
    {
      "rephrased_text": "string"
    }
    ```
    *   `rephrased_text` (string): The final rephrased text with original entities preserved.

**Example (FastAPI Structure)**:

```python
from fastapi import FastAPI, HTTPException
from pydantic import BaseModel
import spacy
from transformers import T5Tokenizer, T5ForConditionalGeneration
import torch
import os

# --- 1. Load Models ---
# Define paths relative to where your backend will run
T5_MODEL_PATH = "./entity_rephraser_model"
SPACY_MODEL_PATH = "./entity_ner_model"

try:
    nlp = spacy.load(SPACY_MODEL_PATH)
    tokenizer = T5Tokenizer.from_pretrained(T5_MODEL_PATH)
    model = T5ForConditionalGeneration.from_pretrained(T5_MODEL_PATH)
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    model.to(device)
    model.eval()
    print("Models loaded successfully!")
except Exception as e:
    print(f"Error loading models: {e}")
    # Depending on deployment, you might want to exit or handle gracefully
    raise RuntimeError("Failed to load AI models, exiting.")

# --- 2. Utility Functions (as defined above) ---
# Copy mask_entities and restore_entities here
def mask_entities(...):
    # ... implementation ...
    pass

def restore_entities(...):
    # ... implementation ...
    pass

# --- 3. API Setup ---
app = FastAPI()

class RephraseRequest(BaseModel):
    text: str

class RephraseResponse(BaseModel):
    rephrased_text: str

@app.post("/api/rephrase", response_model=RephraseResponse)
async def rephrase_text_endpoint(request: RephraseRequest):
    try:
        # Step 1: Detect entities
        doc = nlp(request.text)
        
        # Step 2: Mask entities
        masked_text, entity_map = mask_entities(request.text, doc)
        
        # Step 3: Prepare T5 input
        instruction = (
            "Instruction: Rewrite the Agile idea clearly and professionally. "
            "Do not modify ENTITY tokens. Tone: neutral.\n"
            f"Input: {masked_text}"
        )
        
        # Step 4: T5 Generation
        input_ids = tokenizer(instruction, return_tensors="pt").input_ids.to(device)
        with torch.no_grad():
            outputs = model.generate(input_ids, max_length=128, num_beams=5, early_stopping=True)
        generated_masked_text = tokenizer.decode(outputs[0], skip_special_tokens=True)
        
        # Step 5: Restore entities
        final_rephrased_text = restore_entities(generated_masked_text, entity_map)
        
        return RephraseResponse(rephrased_text=final_rephrased_text)
    except Exception as e:
        raise HTTPException(status_code=500, detail=f"Internal server error: {e}")

# To run with uvicorn:
# uvicorn main:app --host 0.0.0.0 --port 8000
```

---END COPILOT PROMPT---
```

Entity preservation score
"""

# =====================================
# ENTITY PRESERVATION ACCURACY METRIC
# =====================================

def entity_preservation_score(original_text, generated_text, nlp):
    """
    Checks whether all entities in original_text
    are preserved in generated_text.
    """
    original_doc = nlp(original_text)
    original_entities = {ent.text for ent in original_doc.ents}

    preserved = 0
    for ent in original_entities:
        if ent in generated_text:
            preserved += 1

    if len(original_entities) == 0:
        return 1.0

    return preserved / len(original_entities)

"""Evaluate Entity Preservation on Gold Data"""

# =====================================
# ENTITY PRESERVATION EVALUATION
# =====================================

model.eval()  # eval mode
scores = []

with torch.no_grad():
    for item in gold_data[:100]:  # evaluate on 100 samples for speed
        text = item["text"]

        doc = nlp(text)
        masked_text, entity_map = mask_entities(text, doc)

        input_text = (
            "Instruction: Rewrite the Agile idea clearly and professionally. "
            "Do not modify ENTITY tokens. Tone: neutral.\nInput: " + masked_text
        )

        # Move inputs to the same device as the model
        input_ids = tokenizer(input_text, return_tensors="pt").input_ids.to(model.device)

        outputs = model.generate(input_ids, max_length=128)

        generated = tokenizer.decode(outputs[0], skip_special_tokens=True)
        restored = restore_entities(generated, entity_map)

        score = entity_preservation_score(text, restored, nlp)
        scores.append(score)

print("===== ENTITY PRESERVATION RESULTS =====")
print("Average Preservation Accuracy:", round(sum(scores) / len(scores), 3))

"""BLEU / ROUGE"""

import evaluate

# Load the BLEU metric from the 'evaluate' library.
bleu = evaluate.load("bleu")
# Load the ROUGE metric from the 'evaluate' library.
rouge = evaluate.load("rouge")

# Define example predictions and references for evaluation.
preds = ["The API failure is related to Sprint 5 and requires attention under issue BUG-123."]
refs = [["The API failure is related to Sprint 5 and requires attention under issue BUG-123."]]

# Compute and print the BLEU score.
print("BLEU:", bleu.compute(predictions=preds, references=refs))
# Compute and print the ROUGE score.
print("ROUGE:", rouge.compute(predictions=preds, references=refs))

"""SAVE & EXPORT MODELS (FOR FASTAPI)"""

# Save the fine-tuned T5 model to a local directory.
model.save_pretrained("entity_rephraser_model")
# Save the tokenizer to the same local directory.
tokenizer.save_pretrained("entity_rephraser_model")

# Save the trained spaCy NLP pipeline, including custom entity rules, to disk.
nlp.to_disk("entity_ner_model")

"""Download"""

# Import the 'files' utility from google.colab to enable downloading files.
from google.colab import files

# Download the saved T5 model directory as a file (likely a compressed archive).
files.download("entity_rephraser_model")
# Download the saved spaCy NER model directory as a file.
files.download("entity_ner_model")

import zipfile
import os
from google.colab import files

output_zip_filename = "finetuned_models.zip"

# Create a ZipFile object
with zipfile.ZipFile(output_zip_filename, 'w', zipfile.ZIP_DEFLATED) as zipf:
    # Add entity_rephraser_model directory
    for root, _, filenames in os.walk('entity_rephraser_model'):
        for filename in filenames:
            file_path = os.path.join(root, filename)
            arcname = os.path.relpath(file_path, 'entity_rephraser_model')
            zipf.write(file_path, os.path.join('entity_rephraser_model', arcname))

    # Add entity_ner_model directory
    for root, _, filenames in os.walk('entity_ner_model'):
        for filename in filenames:
            file_path = os.path.join(root, filename)
            arcname = os.path.relpath(file_path, 'entity_ner_model')
            zipf.write(file_path, os.path.join('entity_ner_model', arcname))

print(f"Successfully created {output_zip_filename}")

# Download the created zip file
files.download(output_zip_filename)

import os

print("Contents of current directory:")
print(os.listdir('.'))

print("\nContents of 'entity_rephraser_model':")
print(os.listdir('./entity_rephraser_model'))

print("\nContents of 'entity_ner_model':")
print(os.listdir('./entity_ner_model'))