# -*- coding: utf-8 -*-
"""hesitation_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Fz2qYvGRLQIyxRIerDHdTGmWROC8AUUt

Import required libraries
"""

# Import core libraries for data handling
import pandas as pd
import numpy as np

# Import machine learning components
from sklearn.ensemble import IsolationForest
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import (
    accuracy_score,
    classification_report,
    confusion_matrix,
    roc_auc_score,
    ConfusionMatrixDisplay
)

# Import visualization and utilities
import matplotlib.pyplot as plt
import joblib
from google.colab import files

# Set default figure size for plots
plt.rcParams["figure.figsize"] = (8, 6)

"""Upload required CSV files"""

# Upload datasets:
# 1. Frequency Dataset.csv (original data)
# 2. manual_annotation_annotated.csv (manually labeled ground truth)

print("Upload the following files:")
print("1. Frequency Dataset.csv")
print("2. manual_annotation_annotated.csv")

uploaded = files.upload()

"""Load datasets"""

# Load the main frequency dataset
freq_df = pd.read_csv("Frequency Dataset.csv", sep=";")

# Load manually annotated dataset
annot_df = pd.read_csv("manual_annotation_annotated.csv")

print("Frequency Dataset shape:", freq_df.shape)
print("Annotated Dataset shape:", annot_df.shape)

"""Feature cleaning and engineering"""

# Keep only completed typing sessions
freq_df = freq_df.dropna(subset=["TotTime"])

# Convert relevant columns to numeric
freq_df["delFreq"] = pd.to_numeric(freq_df["delFreq"], errors="coerce").fillna(0)
freq_df["leftFreq"] = pd.to_numeric(freq_df["leftFreq"], errors="coerce").fillna(0)
freq_df["TotTime"] = pd.to_numeric(freq_df["TotTime"], errors="coerce")

# Create derived hesitation-related features
freq_df["backspace_ratio"] = freq_df["delFreq"] / (freq_df["TotTime"] / 1000 + 1)
freq_df["correction_rate"] = (
    freq_df["delFreq"] + freq_df["leftFreq"]
) / (freq_df["TotTime"] / 1000 + 1)

# Select final feature set
features = [
    "delFreq",
    "leftFreq",
    "TotTime",
    "backspace_ratio",
    "correction_rate"
]

X = freq_df[features].fillna(0)

print("Feature engineering completed.")

"""Feature scaling"""

# Scale features to zero mean and unit variance
# This is important for Isolation Forest performance
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

print("Feature scaling completed.")

"""Train Isolation Forest model"""

# Initialize Isolation Forest
# contamination=0.2 assumes ~20% of sessions are hesitant
model = IsolationForest(
    contamination=0.2,
    random_state=42,
    n_estimators=200
)

# Train the model
model.fit(X_scaled)

# Generate anomaly scores and predictions
freq_df["hesitation_score"] = model.decision_function(X_scaled)
freq_df["is_hesitant"] = model.predict(X_scaled)

print("Isolation Forest model trained successfully.")

"""Merge predictions with manual annotations"""

# Merge manual labels with model predictions
eval_df = annot_df.merge(
    freq_df[["User ID", "textIndex", "hesitation_score", "is_hesitant"]],
    on=["User ID", "textIndex"],
    how="inner"
)

# Convert labels to binary format
# manual_label: 1 = hesitant, 0 = normal
eval_df["y_true"] = eval_df["manual_label"]

# Model output: -1 = hesitant → convert to 1
eval_df["y_pred"] = (eval_df["is_hesitant"] == -1).astype(int)

print("Evaluation dataset prepared.")
print("Number of evaluation samples:", eval_df.shape[0])

"""Compute evaluation metrics"""

# Calculate accuracy
accuracy = accuracy_score(eval_df["y_true"], eval_df["y_pred"])

# Calculate ROC-AUC using hesitation scores
# Lower score = more anomalous, so we negate it
roc_auc = roc_auc_score(
    eval_df["y_true"],
    -eval_df["hesitation_score"]
)

print("===== MODEL EVALUATION RESULTS =====")
print(f"Accuracy : {accuracy:.3f}")
print(f"ROC-AUC  : {roc_auc:.3f}\n")

# Detailed classification metrics
print("Classification Report:")
print(classification_report(eval_df["y_true"], eval_df["y_pred"]))

"""## Model Description: Isolation Forest

This notebook utilizes the **Isolation Forest** algorithm for anomaly detection to identify "hesitant" typing sessions. Here's a brief overview:

### What is Isolation Forest?
Isolation Forest is an unsupervised machine learning algorithm primarily used for anomaly detection (also known as outlier detection). It works on the principle that anomalies are "few and different" and therefore easier to isolate than normal data points.

Unlike many other anomaly detection methods that try to profile normal data points, Isolation Forest directly tries to isolate anomalies.

### How it Works (Briefly):
1.  **Random Partitions:** It builds an ensemble of Isolation Trees, similar to Random Forests. Each tree is constructed by recursively partitioning the data points into smaller subsets. The partitioning is done by randomly selecting a feature and then a random split value for that feature, between the minimum and maximum values of the selected feature.
2.  **Isolation:** Anomalies, being fewer and having different attribute values, require fewer random partitions to be isolated from the rest of the data. Normal points, being more clustered, require more partitions to be isolated.
3.  **Anomaly Score:** The number of splits required to isolate a data point is used to calculate an anomaly score. Data points that require fewer splits to be isolated are considered more anomalous.

### Why Isolation Forest for Hesitation Detection?

*   **Unsupervised Learning:** Hesitant typing sessions might not always have clear, labeled examples, making supervised learning challenging. Isolation Forest excels in unsupervised settings where it can learn directly from the data patterns without needing pre-labeled anomalies for training.
*   **Efficiency:** It has a relatively low linear time complexity and a small memory footprint, making it efficient for large datasets.
*   **Effective for High-Dimensional Data:** It performs well in datasets with many features, as it can leverage the isolation properties across different dimensions.
*   **Direct Anomaly Detection:** Instead of learning normal behavior and then flagging deviations, it directly focuses on isolating anomalies, which aligns well with the goal of identifying unusual (hesitant) typing patterns.

Confusion matrix visualization
"""

# Create confusion matrix
cm = confusion_matrix(eval_df["y_true"], eval_df["y_pred"])

# Display confusion matrix
disp = ConfusionMatrixDisplay(
    confusion_matrix=cm,
    display_labels=["Normal", "Hesitant"]
)

disp.plot(cmap="Blues")
plt.title("Confusion Matrix: Manual Labels vs Model Predictions")
plt.show()

"""Hesitation score distribution visualization"""

# Plot hesitation score distributions for each class
plt.hist(
    eval_df[eval_df["y_true"] == 0]["hesitation_score"],
    bins=30,
    alpha=0.6,
    label="Normal"
)

plt.hist(
    eval_df[eval_df["y_true"] == 1]["hesitation_score"],
    bins=30,
    alpha=0.6,
    label="Hesitant"
)

plt.xlabel("Hesitation Score (Lower = More Hesitant)")
plt.ylabel("Number of Sessions")
plt.title("Hesitation Score Distribution by Manual Label")
plt.legend()
plt.show()

"""Save and download model & scaler"""

# Save trained model and scaler
joblib.dump(model, "hesitation_model.pkl")
joblib.dump(scaler, "scaler.pkl")

# Download files
files.download("hesitation_model.pkl")
files.download("scaler.pkl")

print("Model and scaler saved and downloaded successfully.")