# -*- coding: utf-8 -*-
"""hesitation_speech_model.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1KDs95QN3fHzH6VlMTTCVn54_wiPJM4W2

CELL 1 — Install Libraries
"""

!pip install datasets
!pip install librosa
!pip install soundfile
!pip install torch torchvision torchaudio
!pip install scikit-learn
!pip install tqdm

"""CELL 2 — Imports"""

import torch
import torch.nn as nn
import numpy as np
import librosa
from datasets import load_dataset
from sklearn.model_selection import train_test_split
from sklearn.metrics import classification_report, accuracy_score
from torch.utils.data import Dataset, DataLoader
from tqdm import tqdm

from huggingface_hub import notebook_login
notebook_login()

from google.colab import drive
drive.mount('/content/drive')

import os

DATA_PATH = "/content/drive/MyDrive/hesitation_dataset"

os.makedirs(DATA_PATH, exist_ok=True)

print("Dataset cache folder ready:", DATA_PATH)

"""CELL 3 — Load Datasets"""

from datasets import load_dataset
from itertools import islice

# Streaming mode – no full download
dataset_stream = load_dataset(
    "amaai-lab/DisfluencySpeech",
    split="train",
    streaming=True
)

# Take only the first 3000 examples
samples = list(islice(dataset_stream, 3000))

print("Total samples loaded:", len(samples))

# Convert to your desired format
data = []

for sample in samples:
    data.append({
        "audio": sample["audio"]["array"],
        "sr": sample["audio"]["sampling_rate"],
        "text":  sample["transcript_annotated"]
    })

print("Total processed samples:", len(data))

print(dataset_stream[0])

"""CELL 4 — Combine Data"""

data = []

for sample in samples:
    data.append({
        "audio": sample["audio"]["array"],
        "sr": sample["audio"]["sampling_rate"],
        "text":  sample["transcript_annotated"]
    })

print("Total samples:", len(data))

"""CELL 5 — Hesitation Labels"""

import re

fillers = ["um","uh","er","ah","hmm","like",
    "you know","i mean","sort of","kind of",
    "well","actually","basically"]

def label_text(text):

    text = text.lower()

    words = re.findall(r"\b\w+\b", text)

    for w in words:
        if w in fillers:
            return 1

    return 0


labels = [label_text(d["text"]) for d in data]

print("Hesitation samples:", sum(labels))
print("Clean speech samples:", len(labels) - sum(labels))

"""CELL 6 — Advanced Feature Extraction"""

import librosa
import numpy as np

def extract_features(audio, sr):

    # -----------------------------
    # 1 Normalize audio
    # -----------------------------
    audio = librosa.util.normalize(audio)

    # -----------------------------
    # 2 Ensure fixed 5 second length
    # -----------------------------
    max_len = sr * 5

    if len(audio) > max_len:
        audio = audio[:max_len]
    else:
        pad = max_len - len(audio)
        audio = np.pad(audio, (0, pad))

    # -----------------------------
    # 3 Extract MFCC
    # -----------------------------
    mfcc = librosa.feature.mfcc(
        y=audio,
        sr=sr,
        n_mfcc=40
    )

    # -----------------------------
    # 4 Delta MFCC (speech dynamics)
    # -----------------------------
    delta = librosa.feature.delta(mfcc)

    # -----------------------------
    # 5 Chroma Features (pitch info)
    # -----------------------------
    chroma = librosa.feature.chroma_stft(
        y=audio,
        sr=sr
    )

    # -----------------------------
    # 6 Stack all features
    # -----------------------------
    features = np.vstack([mfcc, delta, chroma])

    # -----------------------------
    # 7 Force fixed frame width
    # -----------------------------
    max_frames = 216

    if features.shape[1] > max_frames:
        features = features[:, :max_frames]
    else:
        pad_width = max_frames - features.shape[1]
        features = np.pad(features, ((0,0),(0,pad_width)))

    return features.T  # ← ADD .T HERE → shape becomes [216, 92]

"""CELL 7 — Dataset Preparation"""

from tqdm import tqdm
import random

random.shuffle(data)

X = []
y = []

for sample in tqdm(data[:3000]):

    try:
        audio = sample["audio"]
        sr = sample["sr"]
        text = sample["text"]

        label = label_text(text)

        features = extract_features(audio, sr)

        X.append(features)
        y.append(label)

    except:
        continue


print("Total samples:", len(X))
print("Hesitation:", sum(y))
print("Fluent:", len(y) - sum(y))

"""CELL 8 — Padding Sequences"""

from tensorflow.keras.preprocessing.sequence import pad_sequences

X_padded = pad_sequences(
    X,
    padding='post',
    dtype='float32'
)

y = np.array(y)

print(X_padded.shape)

"""CELL 9 — Train Test Split"""

X_train, X_test, y_train, y_test = train_test_split(
    X_padded,
    y,
    test_size=0.2,
    random_state=42
)

"""CELL 10 — PyTorch Dataset"""

class SpeechDataset(Dataset):

    def __init__(self, X, y):

        self.X = torch.tensor(X, dtype=torch.float32)
        self.y = torch.tensor(y, dtype=torch.long)

    def __len__(self):
        return len(self.X)

    def __getitem__(self, idx):
        return self.X[idx], self.y[idx]

"""CELL 11 — DataLoader"""

train_loader = DataLoader(
    SpeechDataset(X_train, y_train),
    batch_size=16,
    shuffle=True
)

test_loader = DataLoader(
    SpeechDataset(X_test, y_test),
    batch_size=16
)

"""CELL 12 — Attention Layer"""

class Attention(nn.Module):

    def __init__(self, hidden_dim):
        super().__init__()

        self.attn = nn.Linear(hidden_dim,1)

    def forward(self, x):

        weights = torch.softmax(self.attn(x), dim=1)

        context = (x * weights).sum(dim=1)

        return context

"""CELL 13 — Strong CNN + BiLSTM Model"""

class HesitationModel(nn.Module):

    def __init__(self, input_size=92):  # pass your actual feature count
        super().__init__()

        self.conv1 = nn.Conv1d(input_size, 64, 3, padding=1)  # ← fix
        self.conv2 = nn.Conv1d(64, 128, 3, padding=1)

        self.relu = nn.ReLU()

        self.lstm = nn.LSTM(
            input_size=128,
            hidden_size=128,
            batch_first=True,
            bidirectional=True
        )

        self.attention = Attention(256)
        self.fc = nn.Linear(256, 2)

    def forward(self, x):
        # x: [batch, seq_len, features] e.g. [16, 216, 92]
        x = x.permute(0, 2, 1)          # → [batch, features, seq_len]

        x = self.relu(self.conv1(x))    # → [batch, 64, seq_len]
        x = self.relu(self.conv2(x))    # → [batch, 128, seq_len]

        x = x.permute(0, 2, 1)          # → [batch, seq_len, 128]

        lstm_out, _ = self.lstm(x)      # → [batch, seq_len, 256]

        x = self.attention(lstm_out)
        x = self.fc(x)
        return x

model = HesitationModel(input_size=92)

"""CELL 14 — Training Setup"""

model = HesitationModel(input_size=92)  # ← was HesitationModel() with no args

criterion = nn.CrossEntropyLoss()

optimizer = torch.optim.Adam(
    model.parameters(),
    lr=0.0005
)

for X_batch, y_batch in train_loader:
    print("X_batch shape:", X_batch.shape)   # ← look here!
    # If using GPU: print(X_batch.device)
    break   # just first batch

"""CELL 15 — Training Loop"""

EPOCHS = 15

for epoch in range(EPOCHS):

    total_loss = 0

    for X_batch,y_batch in train_loader:

        optimizer.zero_grad()

        outputs = model(X_batch)

        loss = criterion(outputs,y_batch)

        loss.backward()

        optimizer.step()

        total_loss += loss.item()

    print("Epoch",epoch+1,"Loss:",total_loss)

"""CELL 16 — Evaluation"""

model.eval()

preds=[]
true=[]

with torch.no_grad():

    for X_batch,y_batch in test_loader:

        outputs=model(X_batch)

        p=torch.argmax(outputs,1)

        preds.extend(p.numpy())
        true.extend(y_batch.numpy())

"""CELL 17 — Metrics"""

print("Accuracy:",accuracy_score(true,preds))

print(classification_report(true,preds))

"""CELL 18 — Save Model"""

torch.save(model.state_dict(),"speech_hesitation_model.pth")

from google.colab import files
files.download("speech_hesitation_model.pth")